services:
  caddy:
    container_name: caddy
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    image: lucaslorentz/caddy-docker-proxy:2.9.1-alpine
    networks:
      - caddy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
  portainer:
    container_name: portainer
    expose:
      - 9000
    image: portainer/portainer-ce:latest
    labels:
      caddy: j11c106.p.ssafy.io
      caddy.handle_path: /portainer/*
      caddy.handle_path.0_reverse_proxy: "{{ upstreams 9000 }}"
      caddy.redir: /portainer /portainer/
    networks:
      - caddy
    pull_policy: always
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  jenkins:
    container_name: jenkins
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    expose:
      - 8080
    image: jenkins/jenkins:latest
    labels:
      caddy: j11c106.p.ssafy.io
      caddy.handle: /jenkins*
      caddy.handle.reverse_proxy: "{{ upstreams 8080 }}"
    networks:
      - caddy
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home

volumes:
  caddy_data:
    name: caddy_data
  portainer_data:
    name: portainer_data
  jenkins_data:
    name: jenkins_data

networks:
  caddy:
    name: caddy