services:
  mongodb-ce:
    container_name: mongodb
    expose:
      - 27017
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    networks:
      - caddy
    pull_policy: always
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
  mysql:
    container_name: mysql
    environment:
      MYSQL_DATABASE: health
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - 31060:3306
    labels:
      caddy: localhost:31060
      caddy.reverse_proxy: "{{ upstreams 3306 }}"
    image: mysql:8.0
    networks:
      - caddy
    pull_policy: always
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    name: mysql_data

networks:
  caddy:
    name: caddy
    external: true